image: hashicorp/terraform

pipelines:
  default:
      - step:
            name: Test
            script:
              - ls -la
              - chdir EC2
              - export AWS_ACCESS_KEY_ID=$ACCESS_KEY
              - export AWS_SECRET_ACCESS_KEY=$SECRET_KEY
              - pwd
              - terraform init
              - terraform validate
              - terraform plan
              - terraform apply --auto-approve
              - terraform destroy --auto-approve
  
